### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Gowixx** [Hexiro/autorequests#1]
```
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/bin/autorequests", line 5, in <module>
    from autorequests.__main__ import main
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/autorequests/__main__.py", line 6, in <module>
    from .classes import URL, Body, Method, Class
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/autorequests/classes/__init__.py", line 8, in <module>
    from .method import Method
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/autorequests/classes/method.py", line 2, in <module>
    from ..utils import format_dict, indent
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/autorequests/utils.py", line 9, in <module>
    def compare_dicts(dicts: list[dict]) -> dict:
TypeError: 'type' object is not subscriptable
~/R$ 
```

**Comment by Hexiro** [comment]
I believe this is just a side effect of typehints in python 3.5. Is that what version you're using?

**Comment by Hexiro** [comment]
I could reproduce on python 3.6.8 so I'll have to fix that

**Comment by Hexiro** [comment]
Okay! I believe all issues with backwards compatibility should be fixed now. If you find any more, feel free to let me know.
